spring:
  application:
    name: BackGp
  datasource:
    url: jdbc:mysql://localhost:3306/gpmonde_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "memko021@gmail.com"
#    password: "mnzn abks ezlz dsdz"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            trust: "*"

  mail:
    host: mail.gpmonde.com
    port: 587
    username: contact@gpmonde.com
    password: Gpmonde@2025
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
      mail.smtp.localhost: gpmonde.com  # 👈 AJOUTEZ CETTE LIGNE
      mail.smtp.from: contact@gpmonde.com  # 👈 ET CELLE-CI

  # Configuration pour l'upload de fichiers
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

jwt:
  secret: "ojJMx7uTkjO3Ov5BOjUimTFkk5Nb+zXvW+6wSRQUqSZeR9OjhseXki3vSA055PApH5ApNPXngdkkFfwOtax4eg=="

# Configuration personnalisée pour le stockage des fichiers
app:
  upload:
    dir: "uploads"

logging:
  level:
    org:
      springdoc: DEBUG
      springframework:
        web: DEBUG
      io:
        swagger.v3: DEBUG