spring:
  application:
    name: BackGp
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/gpmonde_db}
    username: ${SPRING_DATASOURCE_USERNAME:user_gpmonde}
    password: ${SPRING_DATASOURCE_PASSWORD:GpMonde@2022}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: "memko021@gmail.com"
    password: "mnzn abks ezlz dsdz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Configuration pour l'upload de fichiers
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  forward-headers-strategy: framework

# Configuration personnalisée pour le stockage des fichiers
app:
  upload:
    dir: "/uploads"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file:
    name: /app/logs/backgp.log
    max-size: 10MB